#!/usr/bin/env bash
set -euo pipefail
BASE="${1:-http://124.156.137.236}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
curl -fsSL "$BASE/docs/customer-generation-api.html?v=admin-combined-fixes-202605280946" -o "$TMP/customer.html"
curl -fsSL "$BASE/docs/enterprise-generation-api.html?v=admin-combined-fixes-202605280946" -o "$TMP/enterprise.html"
curl -fsSL "$BASE/image-studio-canvas-next.html?v=admin-combined-fixes-202605280946" -o "$TMP/canvas.html"
curl -fsSL "$BASE/canvas-next/tapnow-rewrite.css?v=admin-combined-fixes-202605280946" -o "$TMP/tapnow-rewrite.css"
grep -q "AI 智能体可直接调试版" "$TMP/customer.html"
grep -q "/api/open/personal/generation/tasks" "$TMP/customer.html"
grep -q "canvas_gpt-image-2-pro" "$TMP/customer.html"
grep -q "canvas_sora-v3-pro" "$TMP/customer.html"
grep -q "/api/personal-api-tokens" "$TMP/customer.html"
grep -q "创建和复制企业 API Token" "$TMP/enterprise.html"
grep -q "canvas-sora-v3-pro" "$TMP/enterprise.html"
grep -q "img2video" "$TMP/customer.html"
grep -q "assetCategory:'panorama'" "$TMP/canvas.html"
grep -q "openPersonalApiDocsModal" "$TMP/canvas.html"
grep -q "画布文档快捷创建 API Key" "$TMP/canvas.html"
grep -q "/api/personal-api-tokens" "$TMP/canvas.html"
grep -q "overflow-x:auto" "$TMP/tapnow-rewrite.css"
grep -q "width:max-content" "$TMP/tapnow-rewrite.css"
grep -q "flex:0 0 auto" "$TMP/tapnow-rewrite.css"
grep -q "全景图已导入 720 查看节点" "$TMP/canvas.html"
grep -q "cancelRunNode" "$TMP/canvas.html"
grep -q "停止生成" "$TMP/canvas.html"
grep -q "视频生成等待超时" "$TMP/canvas.html"
grep -q "生成失败，可修改提示词后重新生成" "$TMP/canvas.html"
grep -q "textPromptAgent" "$TMP/canvas.html"
grep -q "assetDesign" "$TMP/canvas.html"
grep -q "文本提示词节点" "$TMP/canvas.html"
grep -q "资产设计节点" "$TMP/canvas.html"
grep -q "/api/workbench/text-agent/run" "$TMP/canvas.html"
grep -q "/api/workbench/asset-design/run" "$TMP/canvas.html"
grep -q "参考图上传接口" "$TMP/customer.html"
grep -q "/v1/files" "$TMP/customer.html"
grep -q "参考图上传接口" "$TMP/enterprise.html"
grep -q "/v1/files" "$TMP/enterprise.html"
grep -q "vn2-ref-token-media" "$TMP/canvas.html"
grep -q "createAudioReferenceNodeFromVideo" "$TMP/canvas.html"
grep -q "finishConnectByNode(n.id);cleanupTempConnections();return;}quickDownstream" "$TMP/canvas.html"
echo "OK verified: $BASE"
